In [1]:
import pandas as pd
import numpy as np

/home/morrowto/.local/lib/python3.10/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)

In [2]:
pd.options.display.float_format = '{:,.2f}'.format
df = pd.read_json('../../data/auto.json')
df

        CarNumber  Refund     Fines    Make    Model
0    Y163O8161RUS       2  3,200.00    Ford    Focus
1     E432XX77RUS       1  6,500.00  Toyota    Camry
2     7184TT36RUS       1  2,100.00    Ford    Focus
3    X582HE161RUS       2  2,000.00    Ford    Focus
5    92918M178RUS       1  5,700.00    Ford    Focus
..            ...     ...       ...     ...      ...
926  Y163O8161RUS       2  1,600.00    Ford    Focus
927  M0309X197RUS       1 22,300.00    Ford    Focus
928  O673E8197RUS       2    600.00    Ford    Focus
929  8610T8154RUS       1  2,000.00    Ford    Focus
930  H419XE197RUS       2  8,594.59  Toyota  Corolla

[725 rows x 5 columns]

In [3]:
sample = df[['CarNumber', 'Make', 'Model']].sample(n=200, replace=True, random_state=21)
sample['Fines'] = np.random.choice(df['Fines'], size=200, replace=True)
sample['Refund'] = np.random.choice(df['Refund'], size=200, replace=True)
concat_rows = pd.concat([df, sample], ignore_index=True)
concat_rows

        CarNumber  Refund     Fines        Make   Model
0    Y163O8161RUS       2  3,200.00        Ford   Focus
1     E432XX77RUS       1  6,500.00      Toyota   Camry
2     7184TT36RUS       1  2,100.00        Ford   Focus
3    X582HE161RUS       2  2,000.00        Ford   Focus
4    92918M178RUS       1  5,700.00        Ford   Focus
..            ...     ...       ...         ...     ...
920  M942OT152RUS       2 15,000.00        Ford   Focus
921  Y187O8161RUS       1  4,900.00        Ford   Focus
922  7064C8197RUS       2  4,600.00  Volkswagen  Passat
923  8437XX154RUS       1  2,100.00        Ford   Focus
924   C410X938RUS       2  2,000.00        Ford   Focus

[925 rows x 5 columns]

In [4]:
np.random.seed(21)
'''concat_rows['Year'] = np.random.randint(1980, 2020, size=len(concat_rows))
concat_rows'''
year_series = pd.Series(np.random.randint(1980, 2020, size=len(concat_rows)), name='Year')
fines = pd.concat([concat_rows, year_series], axis=1)
fines

In [5]:
df_names = pd.read_json('../../datasets/surname.json')
df_names.columns = df_names.iloc[0]
df_names = df_names[1:].reset_index(drop=True)

surnames = df_names['NAME'].tolist()

np.random.seed(21)
unique_cars = df['CarNumber'].unique()
random_surnames = np.random.choice(surnames, size=len(unique_cars), replace=True)

owners = pd.DataFrame({'CarNumber': unique_cars, 'SURNAME': random_surnames})

new_fines = pd.DataFrame({
    'CarNumber': ['NEW001', 'NEW002', 'NEW003', 'NEW004', 'NEW005'],
    'Make': ['Toyota', 'Ford', 'Honda', 'BMW', 'Audi'],
    'Model': ['Camry', 'Focus', 'Civic', 'X5', 'A4'],
    'Fines': [500, 1500, 1200, 2000, 1700],
    'Refund': [1, 2, 0, 3, 2],
    'Year': [2010, 2012, 2015, 2018, 2019]
})

fines = pd.concat([fines, new_fines], ignore_index=True)
owners = owners.iloc[:-20]

new_owners = pd.DataFrame({
    'CarNumber': ['UNIQUE01', 'UNIQUE02', 'UNIQUE03'],
    'SURNAME': ['Smith', 'Johnson', 'Williams']
})

owners = pd.concat([owners, new_owners], ignore_index=True)
fines.set_index('CarNumber', inplace=True)
owners.set_index('CarNumber', inplace=True)

df_1 = fines.join(owners, how='inner')
df_2 = fines.join(owners, how='outer')
df_3 = fines.join(owners, how='left')
df_4 = fines.join(owners, how='right')

pivot_table = fines.pivot_table(index='Make', columns='Year', values='Fines', aggfunc='sum')
pivot_table

Year,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Make,,,,,,,,,,,,,,,,,,,,,
Audi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,700.00"
BMW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"3,000.00",NaN,NaN,"8,594.59",NaN,NaN,"8,500.00",NaN
Ford,"58,289.17","413,689.17","177,578.35","85,100.00","100,394.59","117,083.76","87,094.59","112,000.00","121,683.76","103,700.00",...,"137,878.35","81,189.17","128,800.00","175,989.17","136,094.59","201,694.59","132,994.59","254,300.00","461,094.59","67,700.00"
Honda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"1,200.00",NaN,NaN,NaN,NaN
Skoda,"5,300.00",NaN,"6,900.00","11,594.59","4,400.00","10,294.59",600.00,"7,900.00",NaN,"91,400.00",...,"3,100.00",500.00,500.00,"12,694.59","6,200.00","46,394.59",300.00,NaN,"156,200.00","9,500.00"
Toyota,"12,600.00","8,594.59","2,000.00","7,200.00",NaN,NaN,"2,300.00","8,000.00",NaN,"26,400.00",...,"24,500.00","8,594.59","9,094.59",NaN,NaN,NaN,"1,000.00","11,200.00","13,000.00","28,300.00"
Volkswagen,"30,900.00","8,600.00",NaN,"11,794.59","10,300.00","34,800.00","22,400.00","21,600.00",NaN,"9,600.00",...,"9,100.00","31,600.00","3,200.00","36,600.00","1,300.00","81,100.00","2,100.00",NaN,NaN,NaN
Volvo,NaN,NaN,"6,800.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10,200.00"

In [11]:
owners.to_csv('../../data/owners.csv', index=True)
fines.to_csv('../../data/fines.csv', index=True)