In [1]:
import pandas as pd

/home/morrowto/.local/lib/python3.10/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)

In [2]:
df = pd.read_csv('../../data/feed-views.log', sep = '\t', names = ['datetime', 'user'])

In [3]:
df['datetime'] = df['datetime'].astype("datetime64[ns]")

df['datetime'] = df['datetime'].dt.round('s') 
df['year'] = df['datetime'].dt.year
df['month'] = df['datetime'].dt.month
df['day'] = df['datetime'].dt.day
df['hour'] = df['datetime'].dt.hour
df['minute'] = df['datetime'].dt.minute
df['second'] = df['datetime'].dt.second
df

                datetime       user  year  month  day  hour  minute  second
0    2020-04-17 12:01:08      artem  2020      4   17    12       1       8
1    2020-04-17 12:01:24      artem  2020      4   17    12       1      24
2    2020-04-17 12:27:31      artem  2020      4   17    12      27      31
3    2020-04-17 12:35:45      artem  2020      4   17    12      35      45
4    2020-04-17 12:35:53      artem  2020      4   17    12      35      53
...                  ...        ...   ...    ...  ...   ...     ...     ...
1071 2020-05-21 18:45:20  valentina  2020      5   21    18      45      20
1072 2020-05-21 23:03:06      maxim  2020      5   21    23       3       6
1073 2020-05-21 23:23:50      pavel  2020      5   21    23      23      50
1074 2020-05-21 23:49:22      artem  2020      5   21    23      49      22
1075 2020-05-22 10:36:15      artem  2020      5   22    10      36      15

[1076 rows x 8 columns]

In [4]:
df['daytime'] = pd.cut(df['hour'], bins=[0, 4, 7, 11, 17, 20, 24],
                    labels=['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening'],
                    right=False)
df.set_index('user')

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-17 12:01:08,2020,4,17,12,1,8,afternoon
artem,2020-04-17 12:01:24,2020,4,17,12,1,24,afternoon
artem,2020-04-17 12:27:31,2020,4,17,12,27,31,afternoon
artem,2020-04-17 12:35:45,2020,4,17,12,35,45,afternoon
artem,2020-04-17 12:35:53,2020,4,17,12,35,53,afternoon
...,...,...,...,...,...,...,...,...
valentina,2020-05-21 18:45:20,2020,5,21,18,45,20,early evening
maxim,2020-05-21 23:03:06,2020,5,21,23,3,6,evening
pavel,2020-05-21 23:23:50,2020,5,21,23,23,50,evening
artem,2020-05-21 23:49:22,2020,5,21,23,49,22,evening
artem,2020-05-22 10:36:15,2020,5,22,10,36,15,morning

In [5]:
total_elements = df.count()
print(total_elements)

daytime_counts = df['daytime'].value_counts()
daytime_counts

datetime    1076
user        1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

In [6]:
sorted_df = df.sort_values(by=['hour','minute','second'], ascending=True)
sorted_df

,datetime,user,year,month,day,hour,minute,second,daytime
944,2020-05-15 00:00:13,valentina,2020,5,15,0,0,13,night
945,2020-05-15 00:01:05,valentina,2020,5,15,0,1,5,night
563,2020-05-12 00:01:28,pavel,2020,5,12,0,1,28,night
564,2020-05-12 00:01:38,pavel,2020,5,12,0,1,38,night
565,2020-05-12 00:01:55,pavel,2020,5,12,0,1,55,night
...,...,...,...,...,...,...,...,...,...
1074,2020-05-21 23:49:22,artem,2020,5,21,23,49,22,evening
246,2020-05-09 23:53:56,anatoliy,2020,5,9,23,53,56,evening
247,2020-05-09 23:54:54,pavel,2020,5,9,23,54,54,evening
942,2020-05-14 23:58:57,valentina,2020,5,14,23,58,57,evening
943,2020-05-14 23:59:39,alexander,2020,5,14,23,59,39,evening

In [7]:
max_hour_night = df[df['daytime'] == 'night']['hour'].max()
print('max night hour: ', max_hour_night)

min_hour_morning = df[df['daytime'] == 'morning']['hour'].min()
print('min morning hour: ', min_hour_morning)

user_at_max_night_hour = df[df['hour'] == max_hour_night].index[0]
print('user at max night hour: ', user_at_max_night_hour)

user_at_min_morning_hour = df[df['hour'] == min_hour_morning].index[0]
print('user at min morning hour: ', user_at_min_morning_hour)

mode_daytime = df['daytime'].mode().iat[0]
print('mode daytime: ', mode_daytime)

mode_hour = df['hour'].mode().iat[0]
print('mode hour: ', mode_hour)

In [8]:
early_morning = df[df['daytime'] == 'morning'].nsmallest(3, 'hour')
print('earliest hours in the morning usernames:\n', early_morning[['user', 'hour']])

late_night = df[df['daytime'] == 'evening'].nlargest(3, 'hour')
print('\n\nlatest hours in the night usernames:\n',late_night[['user', 'hour']])

In [9]:
stats = df.describe()
print(stats)
q1 = df['hour'].quantile(0.25)
q3 = df['hour'].quantile(0.75)
iqr = q3 - q1
print('\niqr: ', iqr)